# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  node: circleci/node@4.7.0

jobs:
  demoblaze_tests:
    docker:
      - image: 'node:16-bullseye-slim'
        environment:
            TERM: xterm
    working_directory: ~/project
    parallelism: 1
    steps:
      - checkout
      - run: 
          name: Update image
          command: apt-get update
      - run: 
          name: Install image dependencies
          command: apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
      - run: 
          name: Install Cypress depedencies
          command: npm install cypress --save-dev
      - run: 
          name: Install Newman depedencies
          command: npm install newman  --save-dev
      - run: 
          name: Install NPM depedencies
          command: npm install
      - run:
          name: Run Postman Test
          command: npx newman run postman/api_test.json      
          - run:
          name: Run Cypress Test
          command: npm run test
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots

workflows:
  cypress-test:
    jobs:
      - demoblaze_tests